spring.application.name=quantity-measurement-app
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Spring Data JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger Path
springdoc.swagger-ui.path=/swagger-ui.html

# UC18 
# Google OAuth2 Credentials (Replace with your actual keys from Google Cloud Console)
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Configuration (Must be at least 32 characters long for HMAC-SHA256)
jwt.secret=QuantityMeasurementAppSuperSecretKeyThatIsVeryLongAndSecure123!
jwt.expirationMs=86400000